Switch crad with player
SEIIGruppe2/Server pull request #20
Opened 2024-04-24 18:34 UTC by TimonWoelbitsch

2024-04-29 15:10 UTC, paulxyh requested changes
In general: 
* Testfälle fehlen => entweder entsprechende Files aus SonarCloud nehmen oder testen
* `System.out.println` nicht verwenden

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/GameHandler.java
> +
Too many blank lines

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/utils/Player.java
> +    public WebSocketSession getSession() {
Getter already annotated with Lombok -> Getter for session not necessary

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/utils/Player.java
> +
Getter, Setter if not anything special -> with Lombok

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesForSwitchHandler.java
> +            //hier dafür sorgen dass eigener username entfernt wird
Not yet implemented features in code have to be marked with `TODO`

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesForSwitchHandler.java
> +            List<Player> players = GameHandler.getPlayersofGame();
@TimonWoelbitsch 
ACHTUNG: Hier passiert eine Referenzübergabe => Username würde aus der Main Player Liste gelöscht werden
```suggestion
            List<Player> players = List.copyOf(GameHandler.getPlayersofGame());
```

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesHandler.java
> +        /*nur zu testzwecken bis lobby wieder geht
Wenn der Code nicht mehr benötigt wird, rauslöschen (Z 29-36)

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardDeckHandler.java
> +            System.out.println("Test in der handlemessage"+infos[1]);
`System.out.println()` nicht verwenden
```suggestion
            Logger.getLogger("global").info("Test in der handlemessage"+infos[1]);
```

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/utils/Player.java
> +    public void setusername(String username){
CamelCase für Methodennamen

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +    public int getidofcard(String[] meassage){
CamelCase für Methodennamen
```suggestion
    public int getIdOfCard(String[] meassage){
```

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +            int cardid=getidofcard(textfrommessage);
Folgefehler => Methodennamen refactoren siehe unten

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +    public String[]  inhaltvonnachricht(JsonNode msg){
CamelCase für Methodennamen & Methoden in Englisch benennen
```suggestion
    public String[]  readInfosFromMessage(JsonNode msg){ // hier weiter unten bereits vorhanden gewesen => nur body überschreiben
```

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/utils/UtilityMethods.java
> +    public static String findusernameofPlayer(WebSocketSession session){
CamelCase für Methodennamen

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesForSwitchHandler.java
> +
Leerzeilen löschen

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RegisterUsernameHandler.java
> +           for(Player a:players){
`findPlayer` Methode aus der Utils Klasse verwenden => duplicated code

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RegisterUsernameHandler.java
> +                   System.out.println("Username wurde zum Player hinzugefügt");
`System.out.println` mit Logger ersetzen

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/DrawCardHandler.java
> +import at.aau.se2.utils.Player;
import nicht notwendig

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/DrawCardHandler.java
> +import at.aau.se2.handler.game.GameHandler;
import nicht notwendig

2024-04-29 15:10 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/GameHandler.java
> +                System.out.println(entry.getKey() + ": " + entry.getValue());}
Logger statt `System.out.println` verwenden

2024-04-29 17:48 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/handler/game/GameHandler.java
> +
entfernt

2024-04-29 17:48 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/utils/Player.java
> +    public WebSocketSession getSession() {
lombok verwendet

2024-04-29 17:48 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/utils/Player.java
> +
used lombok

2024-04-29 17:57 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesForSwitchHandler.java
> +            //hier dafür sorgen dass eigener username entfernt wird
removed

2024-04-30 18:07 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/handler/game/subhandlers/RegisterUsernameHandler.java
> +                   System.out.println("Username wurde zum Player hinzugefügt");
deleted

2024-04-30 18:07 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/handler/game/subhandlers/DrawCardHandler.java
> +import at.aau.se2.utils.Player;
deleted

2024-04-30 18:08 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/handler/game/subhandlers/DrawCardHandler.java
> +import at.aau.se2.handler.game.GameHandler;
deleted

2024-04-30 18:19 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/handler/game/subhandlers/RegisterUsernameHandler.java
> +           for(Player a:players){
deleted duplicated code

2024-05-02 09:39 UTC, paulxyh requested changes

2024-05-02 09:39 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesForSwitchHandler.java
> +                else{usernames.add(a.getUsername());}
Wenn if-Zweig leer und nur else-Zweig => Bedingung ändern

```suggestion
                if(!a.getSession().equals(session)){
                    usernames.add(a.getUsername());
                }
```

2024-05-02 09:39 UTC, paulxyh commented on src/main/java/at/aau/se2/utils/Player.java
>      private String username;
Username ist einzigartig; kann nicht mehr verändert werden => `final` & kein Setter, stattdessen Übergabe des Username bei Erstellung des Players (via Konstruktion)

2024-05-02 09:39 UTC, paulxyh commented on src/main/java/at/aau/se2/utils/Player.java
>      public String getUsername() {
Unnötig, wenn Lombok `@Getter` verwendet wird

2024-05-02 09:39 UTC, paulxyh commented on src/test/java/at/aau/se2/handler/dummy/RequestUsernamesForSwitchHandlerTest.java
> +    private Lobby lobby;
Unnötiges Lobby-Objekt

2024-05-02 09:39 UTC, paulxyh commented on src/test/java/at/aau/se2/handler/dummy/RequestUsernamesForSwitchHandlerTest.java
> +    WebSocketSession session;
Unnötiges WebSocketSession-Objekt

2024-05-02 09:39 UTC, paulxyh commented on src/test/java/at/aau/se2/handler/dummy/RequestUsernamesForSwitchHandlerTest.java
> +        session = mock(WebSocketSession.class);
Werden beim Testen von `convertToJson` nicht gebraucht

2024-05-02 09:39 UTC, paulxyh commented on src/test/java/at/aau/se2/handler/dummy/SwitchCardDeckHandlerTest.java
> +    private SecureRandom rn;
Unnötiges SecureRandom-Objekt

2024-05-02 09:39 UTC, paulxyh commented on src/test/java/at/aau/se2/handler/dummy/SwitchCardDeckHandlerTest.java
> +    private Lobby lobby;
Unnötiges Lobby-Objekt

2024-05-02 09:39 UTC, paulxyh commented on src/test/java/at/aau/se2/handler/dummy/SwitchCardDeckHandlerTest.java
> +        when(lobby.getGameState()).thenReturn(new GameState());
Für das Testing nicht benötigt

2024-05-02 09:39 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RegisterUsernameHandler.java
> +        try {String username = msg.path("username").asText();
```suggestion
        try {
               String username = msg.path("username").asText();
```

2024-05-02 18:03 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/handler/game/subhandlers/RequestUsernamesForSwitchHandler.java
> +                else{usernames.add(a.getUsername());}
ok

2024-05-02 18:03 UTC, TimonWoelbitsch commented on src/test/java/at/aau/se2/handler/dummy/RequestUsernamesForSwitchHandlerTest.java
> +    private Lobby lobby;
ok

2024-05-02 18:03 UTC, TimonWoelbitsch commented on src/test/java/at/aau/se2/handler/dummy/RequestUsernamesForSwitchHandlerTest.java
> +    WebSocketSession session;
ok

2024-05-02 18:03 UTC, TimonWoelbitsch commented on src/test/java/at/aau/se2/handler/dummy/RequestUsernamesForSwitchHandlerTest.java
> +        session = mock(WebSocketSession.class);
ok

2024-05-02 18:03 UTC, TimonWoelbitsch commented on src/test/java/at/aau/se2/handler/dummy/SwitchCardDeckHandlerTest.java
> +    private SecureRandom rn;
ok

2024-05-02 18:03 UTC, TimonWoelbitsch commented on src/test/java/at/aau/se2/handler/dummy/SwitchCardDeckHandlerTest.java
> +    private Lobby lobby;
ok

2024-05-02 18:03 UTC, TimonWoelbitsch commented on src/test/java/at/aau/se2/handler/dummy/SwitchCardDeckHandlerTest.java
> +        when(lobby.getGameState()).thenReturn(new GameState());
ok

2024-05-02 18:04 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/handler/game/subhandlers/RegisterUsernameHandler.java
> +        try {String username = msg.path("username").asText();
ok

2024-05-02 18:06 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/utils/Player.java
>      public String getUsername() {
gelöscht

2024-05-02 18:06 UTC, TimonWoelbitsch commented on src/main/java/at/aau/se2/utils/Player.java
>      private String username;
wird schwierig weil du das auskommentiert hast und wir den usernamen erst nachdem ein player der session beigetreten ist definieren so wie ich das verstanden habe

2024-05-06 12:41 UTC, paulxyh requested changes

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/utils/Player.java
>      private String username;
Okay

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +    public int getIdOfCard(String[] meassage){
Typo im Parameternamen

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +            return Integer.parseInt(meassage[3]);
Folgefehler aus Typo

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +            return Integer.parseInt(meassage[2]);
Folgefehler aus Typo

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +                    WebSocketSession sessionofusertoswitchwith= p.getSession();
Variablenname zu lang & wenn er so lang ist CamelCase verwenden
```suggestion
                    WebSocketSession switchSession = p.getSession();
```

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +            String usernametoswitchwith=textfrommessage[1];
Variablenname zu lang & CamelCase verwenden!
```suggestion
            String switchUsername = msgContent[1];
```

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +            String[] textfrommessage= messageContent(msg);
Variablenname ändern => CamelCase
```suggestion
            String[] msgContent = messageContent(msg);
```

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +            Actioncard currentcard = null;
CamelCase
```suggestion
            Actioncard currentCard = null;
```

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +            int cardid=getIdOfCard(textfrommessage);
CamelCase
```suggestion
            int cardId=getIdOfCard(textfrommessage);
```

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +                    currentcard=c;
Folgefehler CamelCase

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/SwitchCardPlayerHandler.java
> +    int passiveanswer;
CamelCase

2024-05-06 12:41 UTC, paulxyh commented on src/main/java/at/aau/se2/handler/game/subhandlers/RegisterUsernameHandler.java
> +           Player currentplayer= UtilityMethods.findPlayer(session,players);
CamelCase

2024-05-06 17:23 UTC, paulxyh approved these changes

2024-05-06 17:36 UTC, merged